#!/usr/bin/env python3
"""Interactive demo for the English-to-Venetian translation project.

Loads the prediction files generated by the zero-shot and fine-tuned NLLB
experiments, displays aggregate BLEU and chrF scores, and provides a
sentence-level comparison for a short live presentation.

Run from the repository root with:

    streamlit run scripts/demo_app.py

The demo uses saved predictions and does not load either model at runtime.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd
import sacrebleu
import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from dataset import read_jsonl

DATA_DIR = PROJECT_ROOT / "data" / "normalized"
RESULTS_DIR = PROJECT_ROOT / "data" / "results"

ZERO_SHOT_FILE = RESULTS_DIR / "nllb_zeroshot_predictions.jsonl"
FINE_TUNED_FILE = RESULTS_DIR / "nllb_finetuned_predictions.jsonl"
EVALUATION_FILE = RESULTS_DIR / "evaluation_results.json"

SYSTEM_LABELS = {
    "nllb_zeroshot": "NLLB zero-shot",
    "nllb_finetuned": "NLLB fine-tuned",
}
SYSTEM_ORDER = list(SYSTEM_LABELS.values())

PRESENTATION_VIEW = "Presentation example"
IMPROVEMENT_VIEW = "Largest improvements"
REGRESSION_VIEW = "Largest regressions"
ALL_EXAMPLES_VIEW = "All test examples"

# Selected manually after reviewing all positive sentence-level comparisons.
# The example is neutral, readable, and improves by approximately +5.72 chrF.
PRESENTATION_EXAMPLE_ID = "0582"


def count_jsonl(path: Path) -> int:
    """Count non-empty records in a JSONL file."""
    if not path.exists():
        return 0
    return len(read_jsonl(path))


def require_files(paths: list[Path]) -> None:
    """Raise an informative error when required demo files are missing."""
    missing = [
        str(path.relative_to(PROJECT_ROOT))
        for path in paths
        if not path.exists()
    ]
    if missing:
        joined = ", ".join(missing)
        raise FileNotFoundError(
            f"Missing required demo files: {joined}. "
            "Run the baseline, fine-tuned inference, and evaluation scripts first."
        )


def build_comparisons(
    zero_shot: list[dict], fine_tuned: list[dict]
) -> list[dict]:
    """Join prediction files by record ID and compute sentence-level chrF."""
    fine_tuned_by_id = {record["id"]: record for record in fine_tuned}
    comparisons: list[dict] = []

    for zero_record in zero_shot:
        fine_record = fine_tuned_by_id.get(zero_record["id"])
        if fine_record is None:
            continue

        reference = zero_record["reference"]
        zero_hypothesis = zero_record["hypothesis"]
        fine_hypothesis = fine_record["hypothesis"]

        zero_chrf = sacrebleu.sentence_chrf(
            zero_hypothesis, [reference]
        ).score
        fine_chrf = sacrebleu.sentence_chrf(
            fine_hypothesis, [reference]
        ).score

        comparisons.append(
            {
                "id": zero_record["id"],
                "source_text": zero_record["source_text"],
                "reference": reference,
                "zero_hypothesis": zero_hypothesis,
                "fine_hypothesis": fine_hypothesis,
                "zero_chrf": zero_chrf,
                "fine_chrf": fine_chrf,
                "delta_chrf": fine_chrf - zero_chrf,
                "zero_model": zero_record.get("model", "NLLB zero-shot"),
                "fine_model": fine_record.get("model", "NLLB fine-tuned"),
            }
        )

    return comparisons


@st.cache_data
def load_demo_data() -> tuple[list[dict], dict, dict[str, int]]:
    """Load predictions, aggregate evaluation results, and split sizes."""
    require_files([ZERO_SHOT_FILE, FINE_TUNED_FILE, EVALUATION_FILE])

    zero_shot = read_jsonl(ZERO_SHOT_FILE)
    fine_tuned = read_jsonl(FINE_TUNED_FILE)
    evaluation = json.loads(EVALUATION_FILE.read_text(encoding="utf-8"))
    comparisons = build_comparisons(zero_shot, fine_tuned)

    split_sizes = {
        "train": count_jsonl(DATA_DIR / "train.jsonl"),
        "dev": count_jsonl(DATA_DIR / "dev.jsonl"),
        "test": count_jsonl(DATA_DIR / "test.jsonl"),
    }
    return comparisons, evaluation, split_sizes


def build_metric_table(evaluation: dict) -> pd.DataFrame:
    """Convert saved evaluation results into an ordered display table."""
    systems = evaluation.get("systems", {})
    rows = []

    for system_id, label in SYSTEM_LABELS.items():
        metrics = systems.get(system_id)
        if not metrics:
            continue
        rows.append(
            {
                "System": label,
                "BLEU": metrics.get("bleu"),
                "chrF": metrics.get("chrf"),
                "Sentences": metrics.get("n"),
            }
        )

    return pd.DataFrame(rows)


def filter_comparisons(comparisons: list[dict], view: str) -> list[dict]:
    """Filter and order examples for the selected presentation view."""
    if view == PRESENTATION_VIEW:
        selected = [
            row
            for row in comparisons
            if row["id"] == PRESENTATION_EXAMPLE_ID
        ]
        if selected:
            return selected

        # Keep the demo usable if prediction files are regenerated.
        improved = [
            row
            for row in comparisons
            if row["delta_chrf"] > 0
        ]
        return sorted(
            improved,
            key=lambda row: row["delta_chrf"],
            reverse=True,
        )[:1]

    if view == IMPROVEMENT_VIEW:
        rows = [row for row in comparisons if row["delta_chrf"] > 0]
        return sorted(rows, key=lambda row: row["delta_chrf"], reverse=True)

    if view == REGRESSION_VIEW:
        rows = [row for row in comparisons if row["delta_chrf"] < 0]
        return sorted(rows, key=lambda row: row["delta_chrf"])

    return sorted(comparisons, key=lambda row: row["id"])


def format_example(row: dict) -> str:
    """Build a compact label for the sentence selector."""
    source_text = row["source_text"]
    preview = source_text[:95]
    suffix = "..." if len(source_text) > 95 else ""
    return f'{row["id"]} — {preview}{suffix}'


def render_dataset_summary(split_sizes: dict[str, int]) -> None:
    """Render train, development, and test split sizes."""
    st.subheader("1. Dataset")
    train_col, dev_col, test_col = st.columns(3)
    train_col.metric(
        "Training examples",
        split_sizes["train"],
        help="Parallel sentences used for fine-tuning.",
    )
    dev_col.metric(
        "Development examples",
        split_sizes["dev"],
        help="Held-out sentences used for checkpoint selection.",
    )
    test_col.metric(
        "Test examples",
        split_sizes["test"],
        help="Unseen sentences used for the final comparison.",
    )


def render_metric_chart(metric_table: pd.DataFrame, metric: str) -> None:
    """Render one metric with an explicit, stable system order."""
    chart_data = metric_table[["System", metric]].copy()
    st.vega_lite_chart(
        chart_data,
        {
            "mark": "bar",
            "encoding": {
                "y": {
                    "field": "System",
                    "type": "nominal",
                    "sort": SYSTEM_ORDER,
                    "title": None,
                },
                "x": {
                    "field": metric,
                    "type": "quantitative",
                    "title": metric,
                    "scale": {"zero": True},
                },
                "tooltip": [
                    {"field": "System", "type": "nominal"},
                    {"field": metric, "type": "quantitative", "format": ".2f"},
                ],
            },
            "height": 150,
        },
        use_container_width=True,
    )


def render_aggregate_results(evaluation: dict) -> None:
    """Render corpus-level BLEU and chrF results."""
    st.subheader("2. Aggregate test results")
    metric_table = build_metric_table(evaluation)

    if metric_table.empty:
        st.warning("No aggregate NLLB results were found in the evaluation file.")
        return

    table_col, bleu_col, chrf_col = st.columns([1.4, 1, 1])
    with table_col:
        st.dataframe(metric_table, hide_index=True, use_container_width=True)
    with bleu_col:
        render_metric_chart(metric_table, "BLEU")
    with chrf_col:
        render_metric_chart(metric_table, "chrF")

    systems = evaluation.get("systems", {})
    zero_metrics = systems.get("nllb_zeroshot")
    fine_metrics = systems.get("nllb_finetuned")
    if not zero_metrics or not fine_metrics:
        return

    bleu_delta = fine_metrics["bleu"] - zero_metrics["bleu"]
    chrf_delta = fine_metrics["chrf"] - zero_metrics["chrf"]

    bleu_delta_col, chrf_delta_col = st.columns(2)
    bleu_delta_col.metric("Fine-tuning delta: BLEU", f"{bleu_delta:+.2f}")
    chrf_delta_col.metric("Fine-tuning delta: chrF", f"{chrf_delta:+.2f}")

    if bleu_delta < 0 and chrf_delta < 0:
        st.info(
            "Experimental result: fine-tuning did not improve test-set "
            "generalization. The zero-shot model achieved higher aggregate scores."
        )
    else:
        st.success(
            "Fine-tuning improved at least one aggregate test-set metric."
        )


def render_example_comparison(comparisons: list[dict]) -> None:
    """Render an interactive sentence-level comparison."""
    st.subheader("3. Sentence-level comparison")

    improved = sum(row["delta_chrf"] > 0 for row in comparisons)
    worsened = sum(row["delta_chrf"] < 0 for row in comparisons)
    unchanged = len(comparisons) - improved - worsened

    improved_col, worsened_col, unchanged_col = st.columns(3)
    improved_col.metric("Fine-tuned better", improved)
    worsened_col.metric("Fine-tuned worse", worsened)
    unchanged_col.metric("Equal score", unchanged)

    view = st.radio(
        "Example view",
        [
            PRESENTATION_VIEW,
            IMPROVEMENT_VIEW,
            REGRESSION_VIEW,
            ALL_EXAMPLES_VIEW,
        ],
        horizontal=True,
        help=(
            "Start with the presentation example, then switch to the largest "
            "regressions to show both sides of the result."
        ),
    )
    filtered = filter_comparisons(comparisons, view)

    if not filtered:
        st.info("No examples are available for the selected view.")
        return

    selected_index = st.selectbox(
        "Select a test sentence",
        range(len(filtered)),
        format_func=lambda index: format_example(filtered[index]),
    )
    selected = filtered[selected_index]

    st.markdown("**English source**")
    st.info(selected["source_text"])

    reference_col, zero_col, fine_col = st.columns(3)
    with reference_col:
        st.markdown("**Venetian reference**")
        st.write(selected["reference"])
    with zero_col:
        st.markdown("**NLLB zero-shot**")
        st.write(selected["zero_hypothesis"])
        st.metric(
            "Sentence chrF",
            f'{selected["zero_chrf"]:.2f}',
            help="Exploratory sentence-level score.",
        )
    with fine_col:
        st.markdown("**NLLB fine-tuned**")
        st.write(selected["fine_hypothesis"])
        st.metric(
            "Sentence chrF",
            f'{selected["fine_chrf"]:.2f}',
            delta=f'{selected["delta_chrf"]:+.2f}',
            help="Delta relative to the zero-shot prediction.",
        )

    with st.expander("Technical details"):
        st.write(f'Zero-shot model: `{selected["zero_model"]}`')
        st.write(f'Fine-tuned model: `{selected["fine_model"]}`')
        st.write(
            "Sentence-level chrF is included for exploration only. "
            "The project conclusion is based on corpus-level test metrics."
        )


def main() -> None:
    st.set_page_config(
        page_title="English-to-Venetian Translation Demo",
        layout="wide",
        initial_sidebar_state="collapsed",
    )

    st.title("English-to-Venetian Machine Translation")
    st.caption(
        "A comparison of NLLB-200 zero-shot translation and the same model "
        "after fine-tuning on a small Venetian parallel corpus."
    )

    try:
        comparisons, evaluation, split_sizes = load_demo_data()
    except (FileNotFoundError, json.JSONDecodeError, KeyError) as exc:
        st.error(str(exc))
        st.stop()

    if not comparisons:
        st.error("No matching zero-shot and fine-tuned predictions were found.")
        st.stop()

    render_dataset_summary(split_sizes)
    render_aggregate_results(evaluation)
    render_example_comparison(comparisons)

    st.divider()
    st.markdown(
        "**Takeaway:** fine-tuning was technically successful, but this small "
        "training set did not improve generalization over the zero-shot baseline."
    )


if __name__ == "__main__":
    main()
